### ISSUE TITLE
Always include a clock from a neighbor in the log (regardless of its staleness)

### ISSUE THREAD

**Issue by pittma** [auxoncorp/modality-probe#164]
When a probe receives a neighbor's clock via [`merge_snapshot`](https://github.com/auxoncorp/modality-probe/blob/4b848e493624c84b4330461fd2eb79610ae4e722/src/lib.rs#L306) and that clock is _behind_ the last clock this probe has seen from that neighbor, we discard it:

https://github.com/auxoncorp/modality-probe/blob/4b848e493624c84b4330461fd2eb79610ae4e722/src/history.rs#L294-L304

Which is followed by

https://github.com/auxoncorp/modality-probe/blob/4b848e493624c84b4330461fd2eb79610ae4e722/src/history.rs#L320-L336

in [`write_clocks_to_log`](https://github.com/auxoncorp/modality-probe/blob/4b848e493624c84b4330461fd2eb79610ae4e722/src/history.rs#L312).

However, since the purpose of `modality-probe` is to record what happened while the system was running, we should instead include this older clock in the log as, regardless of the order in which it was received, it still had a causal ripple that needs to be captured. You end up with a graph that looks something like this: 

![ooo](https://user-images.githubusercontent.com/1194436/87075445-346d6200-c1d5-11ea-991b-57c4e3431afc.png)

Which, yeah, is weird—but it is a correct depiction of the actual causal order that occurred while the system is running, and that is probably something that we'd want to know about! If we discard this clock, we lose the ability to find things like this during the analysis of the log.

**Comment by ZackPierce** [comment]
I think it might be better to include both the highest-ever-seen value for a clock and the stale-but-just-received value into the log.

**Comment by pittma** [comment]
> I think it might be better to include both the highest-ever-seen value for a clock and the stale-but-just-received value into the log.

I disagree, and this relates to a larger problem I believe we have in our ability to accurately reconstruct history. To properly assemble a graph of what actually occurred in the SUA (System Under Analysis), the only things we should insert into the log are the things that _happened_. Right now, every time we tick our clock, we use `write_clocks_to_log` to include _all_ of the clocks we've seen so far, but that isn't what actually happened. What happened was that, a) we produced a snapshot, or b) we merged one. To properly capture what happened, we should _only_ include an external clock in the log during a snapshot merge, and only the one coming with that snapshot. This properly represents the interaction that's just occurred. Conversely, when we tick our clock for the production of a snapshot, no external clocks should be included.

Now, I'm not suggesting that we don't also keep a set of all clocks we've seen and their greatest tick value at all, I'm just suggesting that these things do not belong in the event log unless they're representative of an occurrence in the SUA. This is what I meant by untangling "the state I'm keeping for me" (that clock set that may be useful for helping neighbors to catch up or to (someday) help with lost updates) and "the state I'm keeping for you" (the things that go into the log which are a representation of What Happened).

To be clear, I prefer the above approach, but it is not the only one. We could alternatively find a way to make a distinction about the clocks in the log when writing all of them to denote which one was involved in the interaction. For snapshot production, none of the clocks should be marked as such.

**Comment by ZackPierce** [comment]
Ah, I think I see. That's a bit more dramatic change to our log than I originally thought -- making the clock-regions of our reported log include only the "one thing that happened". I presume that change would go hand in hand with including all the clocks at the very beginning of a report (so that one could reconstruct the entire picture that probe has in hand). Overall this means we would store fewer redundant clocks in the probe's log, so that's nice.

That sounds like it could work -- we could reconstruct the entire clock-set relevant to a segment upon collection of a bulk report. There are likely more complicated considerations for a chunked report, but I'll have to think about it some.

**Comment by pittma** [comment]
I'm going to capture a excerpted discussion with myself and @ZackPierce here, as it contains the work that'll get done here:

> **zack 8:52**
> I think the main reason why I like having all the available probe's clocks sent per report
>
> **zack 8:52**
> is helping provide some redundancy to mitigate the effects of a dropped report and to simplify the process of materializing complete segments on the backend
>
> **zack 8:53**
> in our database, I think it's probably useful to have the model where all the relevant clock-values for a region of events are right there, joinable as needed via the causal segment key
>
> **zack 8:55**
> having all the clock-values in the report (even once, at the start) makes the job of producing the full set of relevant clock values for storage per segment significantly easier, IMHO
>
> ** zack 8:57**
> (even if we don't strictly need all the clocks at once to draw the lines between two given segments, having all the clocks available in the storage per segment means that drawing the line between any pair of segments is significantly easier)
>
> **dan  9:23 AM**
> > Thanks for your patience with my tired self yesterday.
>
> Ah, no worries.
>
> > having all the clock-values in the report (even once, at the start) makes the job of producing the full set of relevant clock values for storage per segment significantly easier, IMHO
>
> I'm not sure this is what you're saying, but the clock set being its own thing on a report I think is fine, it's the segment-by-segment clock set that convolutes things. It's tangling two different types of state.
> > (even if we don't strictly need all the clocks at once to draw the lines between two given segments, having all the clocks available in the storage per segment means that drawing the line between any pair of segments is significantly easier)
>
> This point I don't think I understand. When clocks aren't updated, they don't have any bearing w/r/t the causal history for the segment at hand.
>
> An example: If I've cut a new segment because probe C communicated with me with clock 4, so I, probe A, tick my clock to 5 and record both of ours into the log, that makes sense. But to also record the last value I saw for probe B's clock, say 2, is misleading, because we already have that arrow, from when probe B initially sent us their snapshot! What ends up happening is that we amass every transitive arrow, which, yeah, isn't wrong, like semantically, but we don't want to draw those transitive arrows explicitly, we want that part to be something that is inferred by walking the graph.
This has effects, for instance, on query matching because it leads to "skipping". The events from A, segment-clock 5 aren't directly caused by the events from B, segment-clock 2: but when we draw this arrow, we skip where the B -> A communication occurred say (B, 2) -> (A, 4), because we've also drawn an arrow from (B, 2) -> (A, 5). This arrow is the transitive arrow (B, 2) -> (A, 4) -> (A, 5), but that composition will cause query matching to "skip" (A, 4), which is wrong.
>
> **zack  10:06 AM**
My current best-guess at what to do in the reports is switch to a model where we only put all the clocks in at the head of the whole report. Then, for all further communication-occurrences, put in one or two clocks (the recently-ticked self-clock, and, in the case of a merge, also the incoming [possibly stale] neighbor clock) (edited) 
>
> **zack 10:08**
> What we put in the sql storage layer only has to be useful, correct, and ideally, fast
>
> **zack 10:09**
> I think the sql storage stuff is likely going to flex around some as we advance the query engine
>
> **dan  10:10 AM**
> That is exactly what I'd like to do for the reports, and I agree about modality's storage.
>
> **zack  10:11 AM**
> I'm wildly uncertain if this scheme will make things easier or harder for the JTAG world
>
> **dan  10:11 AM**
> If it were up to me, the `LogReport` types would grow a new member, something like `latest_clocks: Vec-ish<LogicalClock>` and then segments would be as stated above.
>
> **zack  10:12 AM**
> probably harder in some ways and easier in others
>
> **dan  10:12 AM**
> Aye, I don't know either.
>
> **zack  10:12 AM**
> As long as we're clear that the lastest-clocks are the latest-clocks before the "diffs" that arrive in the following segments
>
> **zack 10:13**
> Practically speaking, from a reporting implementation perspective, I would still put the header latest-clocks into the log
>
> **zack 10:13**
> (flushed like we do per-report)
>
> **zack 10:14**
> and then just improve the parsing/handling to split out the first clock region (edited) 
>
> **dan  10:14 AM**
> My experience is all in the std world, I've not spent anytime with the probe-side report generation, so I understand your weariness here.
>
> **zack  10:14 AM**
> It's important, especially for the chunking implementation
>
> **zack 10:14**
> weariness and wariness alike
>
> **dan  10:15 AM**
> I'll do this work starting today (with that tiny patch I sent above), and will share insights and questions along the way.
>
> **dan 10:15**
> lol
>
> **dan 10:15**
> whoops, *wariness

**Comment by pittma** [comment]
Closing in favor of #179.
