### ISSUE TITLE
New API: Check if there's anything to report

### ISSUE THREAD

**Issue by mullr** [auxoncorp/modality-probe#186]
In many integration scenarios, it would be useful to be able to check if there are any pending, unreported events before actually calling the `report` api. 
- This is clearly more efficient, which may be important when calling `report` on a frequent timer
- If you want to completely flush the probe's internal event buffer, you need a way to tell that it's done. You can currently do this heuristically by checking if the output buffer has a significant amount of data in it, but this would be much cleaner.

**Comment by nathanaschbacher** [comment]
This seems fairly reasonable to me. I could also see the constituent parts of this being surfaced in combination as a simplification or sugar to turn some version of the `report` function into a no-op in situations where we're in control of the platform integration.

**Comment by nathanaschbacher** [comment]
@jonlamb-gh thoughts?

**Comment by pittma** [comment]
> If you want to completely flush the probe's internal event buffer, you need a way to tell that it's done. You can currently do this heuristically by checking if the output buffer has a significant amount of data in it, but this would be much cleaner.

In the original design for reporting v2 we included something like this:

```rust
struct ReportResult {
    num_log_items: usize,
    num_bytes_written: usize,
}

fn report(&mut self, buffer: &mut [u8]) -> Result<ReportResult, ReportError>;
```

But I ultimately scrapped it because I couldn't remember what the purpose of `num_log_items` was. This must have been it. We should probably put it back regardless if an is-there-anything-to-report function is added to the API or not.

**Comment by jonlamb-gh** [comment]
Sounds pretty convenient to me.
We could also indicate this using the existing `out_written_bytes` value; when equal to zero there are no more items to report.

**Comment by mullr** [comment]
>  We could also indicate this using the existing out_written_bytes value; when equal to zero there are no more items to report.

This unfortunately doesn't work, because when we create a report, we synthesize an event that says "I just made a report!" So every report ends up having at least one event in it, even if there was nothing in the queue.

**Comment by jonlamb-gh** [comment]
> This unfortunately doesn't work, because when we create a report, we synthesize an event that says "I just made a report!" So every report ends up having at least one event in it, even if there was nothing in the queue.

I was imagining that the probe would know how to deal with this; if there's nothing to report, then set `out_bytes_written` to zero and don't log the internal event.

**Comment by mullr** [comment]
> I was imagining that the probe would know how to deal with this; if there's nothing to report, then set out_bytes_written to zero and don't log the internal event.

Oh, I didn't consider that. I think that change may actually be sufficient for both cases, without requiring a new api call.
